apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-5akn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-5akn
    app.kubernetes.io/part-of: tkwch-fix-0075-0069-app
  name: devfile-sample-5akn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-5akn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-5akn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0069-tenant/tkwch-fix-0075-0069-app/devfile-sample-5akn@sha256:8b64f9b4b46b99fd50d2c6ed4f72b584981104c7c5c13cb702641a06867e5ec3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
